version: '2'

services:
  webapp:
    build: ./
    image: amitsaha/flask_app_2
    container_name: webapp 
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./src:/application
  client:
    depends_on:
      - webapp
    build:
      context: ./
      dockerfile: Dockerfile-client
    image: amitsaha/flask_app:client
    container_name: client
